# Generated by Django 3.0.6 on 2020-05-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_auto_20200530_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='goodtext',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
    ]
